### PR TITLE
AMQP-617: Don't alias Queue and Exchange name attr

### PR DESCRIPTION
**Pull request by artembilan**
JIRA: https://jira.spring.io/browse/AMQP-617

If `id` attribute is present don't register a bean alias for the `name` attribute

### CODE REVIEW

**Comment by garyrussell** [comment]
Cool beans! Doc Polish: If you wish to declare a queue and exchange with the same `name`, you must provide an `id`.

**Comment by artembilan** [comment]
Gary,  looks like you have missed the link to the docs.

**Comment by garyrussell** [comment]
Sorry - updated

**Comment by garyrussell** [comment]
I've changed the last sentence...


>There is no change if the element has just a `name` attribute, the bean can still be referenced by the `name`, for example in binding declarations, but you still can't reference it if the name contains SpEL - provide an `id` for reference purposes.

**Comment by artembilan** [comment]
Cool! I'm fine with your polishing, Gary
Thank you!

**Comment by garyrussell** [comment]
Merged as 72ce807fd3f095bf8408fb09e2840896838c580e

**Pull request closed without merging**
