### PR TITLE
AMQP-630: Move dependency from Log4j to Log4j2

### PR DESCRIPTION
**Pull request by artembilan**
JIRA: https://jira.spring.io/browse/AMQP-630

### CODE REVIEW

**Comment by garyrussell** [comment]
Artem, I merged this too soon - we need to remove `log4j.properties` from the test resources and configure `log4j2.xml`.

**Comment by artembilan** [comment]
Doh. Thank you for pointing that out. I will raise a new PR. Will hope the simple renaming will work: https://logging.apache.org/log4j/2.x/manual/configuration.html

**Comment by garyrussell** [comment]
Bear in mind, though that there is already a log4j2.xml in spring-rabbit (for the appender tests).

**Comment by artembilan** [comment]
See #442 for configs migration.

**Pull request merged**
