### PR TITLE
AMQP-479: XA compatibility for RabbitResourceSync

### PR DESCRIPTION
**Pull request by artembilan**
JIRA: https://jira.spring.io/browse/AMQP-479

Note, there is no test-cases on the matter (yet): we need extra dependencies for XA Transaction Manager.

### CODE REVIEW

**Comment by garyrussell** [comment]
Can you not mock a global tx ?

**Comment by artembilan** [comment]
Pushed tests.

**Comment by garyrussell** [comment]
Seeing this (twice) with testAll - strange that travis didn't see it; it's not an LRT...

    org.mockito.exceptions.verification.TooManyActualInvocations: 
    connection.createChannel();
    Wanted 1 time:
    -> at org.springframework.amqp.rabbit.core.RabbitTemplateTests.returnConnectionAfterCommit(RabbitTemplateTests.java:135)
    But was 2 times. Undesired invocation:
    -> at org.springframework.amqp.rabbit.connection.SimpleConnection.createChannel(SimpleConnection.java:44)

   	    at org.springframework.amqp.rabbit.core.RabbitTemplateTests.returnConnectionAfterCommit(RabbitTemplateTests.java:135)

**Comment by artembilan** [comment]
Not sure yet what to do with that sporadic failing test, but logs looks like:
```
2015-11-13 11:46:24,226 DEBUG main [org.springframework.amqp.rabbit.core.RabbitTemplateTests$1] - <Creating new transaction with name [null]: PROPAGATION_REQUIRED,ISOLATION_DEFAULT>
2015-11-13 11:46:24,226 INFO main [org.springframework.amqp.rabbit.connection.CachingConnectionFactory] - <Created new connection: SimpleConnection@4eaf3684 [delegate=Mock for Connection, hashCode: 1076984738]>
2015-11-13 11:46:24,226 DEBUG main [org.springframework.amqp.rabbit.connection.CachingConnectionFactory] - <Creating cached Rabbit Channel from Mock for Channel, hashCode: 1171434979>
2015-11-13 11:46:24,226 DEBUG main [org.springframework.amqp.rabbit.core.RabbitTemplate] - <Executing callback on RabbitMQ Channel: Cached Rabbit Channel: Mock for Channel, hashCode: 1171434979>
2015-11-13 11:46:24,226 DEBUG main [org.springframework.amqp.rabbit.core.RabbitTemplate] - <Publishing message on exchange [], routingKey = [foo]>
2015-11-13 11:46:24,226 TRACE main [org.springframework.amqp.rabbit.core.RabbitTemplateTests$1] - <Triggering beforeCommit synchronization>
2015-11-13 11:46:24,226 TRACE main [org.springframework.amqp.rabbit.core.RabbitTemplateTests$1] - <Triggering beforeCompletion synchronization>
2015-11-13 11:46:24,226 DEBUG main [org.springframework.amqp.rabbit.core.RabbitTemplateTests$1] - <Initiating transaction commit>
2015-11-13 11:46:24,226 TRACE main [org.springframework.amqp.rabbit.core.RabbitTemplateTests$1] - <Triggering afterCommit synchronization>
2015-11-13 11:46:24,226 TRACE main [org.springframework.amqp.rabbit.core.RabbitTemplateTests$1] - <Triggering afterCompletion synchronization>
2015-11-13 11:46:25,227 DEBUG main [org.springframework.amqp.rabbit.core.RabbitTemplateTests$1] - <Creating new transaction with name [null]: PROPAGATION_REQUIRED,ISOLATION_DEFAULT>
2015-11-13 11:46:25,228 DEBUG main [org.springframework.amqp.rabbit.connection.CachingConnectionFactory] - <Creating cached Rabbit Channel from Mock for Channel, hashCode: 1171434979>
2015-11-13 11:46:25,228 DEBUG main [org.springframework.amqp.rabbit.core.RabbitTemplate] - <Executing callback on RabbitMQ Channel: Cached Rabbit Channel: Mock for Channel, hashCode: 1171434979>
2015-11-13 11:46:25,228 DEBUG main [org.springframework.amqp.rabbit.core.RabbitTemplate] - <Publishing message on exchange [], routingKey = [baz]>
2015-11-13 11:46:25,228 TRACE main [org.springframework.amqp.rabbit.core.RabbitTemplateTests$1] - <Triggering beforeCommit synchronization>
2015-11-13 11:46:25,228 TRACE main [org.springframework.amqp.rabbit.core.RabbitTemplateTests$1] - <Triggering beforeCompletion synchronization>
2015-11-13 11:46:25,228 DEBUG main [org.springframework.amqp.rabbit.core.RabbitTemplateTests$1] - <Initiating transaction commit>
2015-11-13 11:46:25,228 TRACE main [org.springframework.amqp.rabbit.core.RabbitTemplateTests$1] - <Triggering afterCommit synchronization>
2015-11-13 11:46:25,228 TRACE main [org.springframework.amqp.rabbit.core.RabbitTemplateTests$1] - <Triggering afterCompletion synchronization>
```
Pay attention for the second
> 2015-11-13 11:46:25,228 DEBUG main [org.springframework.amqp.rabbit.connection.CachingConnectionFactory] - <Creating cached Rabbit Channel from Mock for Channel, hashCode: 1171434979>

I the successful case we have this in between transactions:
```
2015-11-13 11:48:15,505 TRACE main [org.springframework.amqp.rabbit.core.RabbitTemplateTests$1] - <Triggering afterCompletion synchronization>
2015-11-13 11:48:15,509 TRACE main [org.springframework.amqp.rabbit.connection.CachingConnectionFactory] - <Returning cached Channel: Mock for Channel, hashCode: 242355057>
2015-11-13 11:48:16,509 DEBUG main [org.springframework.amqp.rabbit.core.RabbitTemplateTests$1] - <Creating new transaction with name [null]: PROPAGATION_REQUIRED,ISOLATION_DEFAULT>
```
Investigating...

**Comment by artembilan** [comment]
OK. I found the issue. I add to the `ThreadLocal<TransactionInfo>`, but don't clean up in the end.
Since all other TX tests are performed withing the same Thread they see that old value, hence don't behave as expected.
Although it shows me the bug that I don't `releaseResource()` in case of global TX in the end of `afterCompletion()`.
Fixing...

**Comment by artembilan** [comment]
Pushed

**Comment by garyrussell** [comment]
Merged as d550f9dcf96f3bf9967a5e876dac53dd579be560

**Pull request closed without merging**
