### PR TITLE
WIP: Proposal how to solve #1269

### PR DESCRIPTION
**Pull request by KaiStapel**
WIP #1269

Tests missing

### CODE REVIEW

**Review by artembilan — CHANGES_REQUESTED** [review]
Looks good!

Please, consider to modify some existing `@RabbitListener` to satisfy your expectations for a `@Validated` annotation and type inference.

We probably also need to adjust the mentioned docs since there is no limitation anymore.

Thank you for your effort!

**Comment by garyrussell** [comment]
Closing; see https://github.com/spring-projects/spring-amqp/issues/1269#issuecomment-733843525

**Comment by garyrussell** [comment]
Thanks for the contribution.

**Comment by garyrussell** [comment]
By the way, the proposal doesn't work; this one now fails....

```java
@RabbitListener(queues = "test.converted.args1")
public String foo2(Foo2 foo2, @Header("amqp_consumerQueue") String queue) {
	return foo2 + queue;
}
```

**Comment by KaiStapel** [comment]
Yes, sorry. The proposal was only to highlight the position in the code base which I thought had to be adjusted. The change itself was never tested by me (due to lack of time).

**Pull request closed without merging**
