### PR TITLE
Upgrade to Gradle 5

### PR DESCRIPTION
**Pull request by garyrussell**
- annotation processors are now on their own path instead of the compile path
- Log4J's annotation processor detects the appender

### CODE REVIEW

**Comment by artembilan** [comment]
How can we be sure that all plugins we use in the build are really compatible with Gradle 5 and works well?

Thanks

**Comment by garyrussell** [comment]
Good point; I am just tired of seeing the deprecation warning; perhaps we should just add the `annotationProcessor` path for now.

**Comment by artembilan** [comment]
I guess we can move to Gradle 5 when Spring Framework is ready on the matter.
Then we can borrow their experience to upgrade/replace appropriate plugins.

**Comment by garyrussell** [comment]
Adding `annotationProcessor` does not stop the deprecation warning; I guess I'll live with it for now.

**Comment by artembilan** [comment]
On the other hand I see that Spring security has done that already: https://github.com/spring-projects/spring-security/issues/6148

So, maybe not so big pain doing that on our side.

I worry more about docs plugins though...

**Pull request closed without merging**
