### PR TITLE
GH-1517: added configuration for multiple customizer for ContainerMessageListener

### PR DESCRIPTION
**Pull request by rfelgent**
This PR is for #1517

### CODE REVIEW

**Comment by rfelgent** [comment]
I am unable to sign the contribute license agreement for my company, as there is no selection item of github organisation.
but this field is required to proceed.
pls help.

**Comment by ilayaperumalg** [comment]
@rfelgent Sorry for the inconvenience. Could you tell us if you are trying to sign as Individual CLA or Corporate CLA?

**Comment by artembilan** [comment]
@rfelgent , 

OK. Tell us, please, then what is wrong with this link to follow:

image

?

**Comment by rfelgent** [comment]
The link itself works . The company drop down selection has  no items. the field is required.

I cant find the mis-configuration / problem on my side...

**Comment by ilayaperumalg** [comment]
@rfelgent I checked with @rwinch and he suggested to check if you have made your membership public as outlined in "How Do I Link My Signature to a GitHub Organization?" https://cla.pivotal.io/about#corporate-signature-github-org ?

**Comment by rfelgent** [comment]
Hello @all,

thanks for your support. I found the mis-configuration my side. Thanks again.

I signed the Corporate CLA

**Comment by garyrussell** [comment]
Thanks for the contribution; looking forward to more; merged as aa86a0292dfca60d468ae15b2b2f946d2e0259c7 (please limit commit headlines to 50 chars in future).

With polishing, test and docs here b9b83f9bf89a05939b62b90b61116a372b5626a8

**Comment by garyrussell** [comment]
...and cherry-picked to 2.4.x.

**Comment by rfelgent** [comment]
thank you very much for your support (checkstyle, documentation and so on) @garyrussell

**Pull request closed without merging**
