### PR TITLE
Changes to build with JDK10

### PR DESCRIPTION
**Pull request by garyrussell**
- update jaCoCo version
- new `Integer(n)` is deprecated
- @PreDestroy no longer present
- SSL change

### CODE REVIEW

**Comment by artembilan** [comment]
> `@PreDestroy` no longer present

That's funny! That's not what Java was all these years... :smile: 

Should I download and install JDK 10 locally as well?

`javax.annotation-api` must be there is CP, though: https://stackoverflow.com/questions/46502001/how-to-get-access-to-javax-annotation-resource-at-run-time-in-java-9.

**Comment by artembilan** [comment]
I wonder if we have to do anything with the Travis config to rely on Java 10 already, but still check compatibility with Java 8.
Although that should be guaranteed by the `sourceCompatibility` and `targetCompatibility` Gradle props.

**Comment by garyrussell** [comment]
>Should I download and install JDK 10 locally as well?

Up to you; I wasn't planning to change the build to use JDK10; I just wanted to make sure our tests pass with it.

OTOH, I suppose changing the build will ensure we don't introduce any new problems.

**Comment by artembilan** [comment]
>  I suppose changing the build will ensure we don't introduce any new problems.

That's correct. So, or Travis or CI plan must be changed to JDK 10 therefore.

I guess we have more similar issues with SI :smile: . However that is already a different story...

**Comment by garyrussell** [comment]
Only had to change JaCoCo for kafka; checking SI now...

**Comment by artembilan** [comment]
One more time:

Are we going to do anything with CI plan or Travis config?

Let me know and this will be ready for merge!

**Comment by garyrussell** [comment]
Looks like it's not supported on travis yet: https://github.com/travis-ci/travis-ci/issues/9368

Let's go ahead and merge; we can defer the build change.

**Pull request merged**
