### PR TITLE
AMQP-783: Can't use blank key/trust store passwords

### PR DESCRIPTION
**Pull request by zadeluca**
https://jira.spring.io/browse/AMQP-783

This has not been commented on yet, but I think it is a pretty benign change so I just went ahead and did it. Please let me know what you think.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@zadeluca Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-amqp&pullRequestId=686)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-amqp&pullRequestId=686) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@zadeluca Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-amqp&pullRequestId=686)!

**Comment by artembilan** [comment]
Thank you for the contribution.

Can you really confirm that the fix works as expected? 
Because I don't see any tests in your fix.

I'm really curious how is it possible to configure empty password instead of null on the target key store.

**Comment by zadeluca** [comment]
It does work for me, I just used `keyStore.passPhrase=` in the properties file

**Comment by artembilan** [comment]
Merged and cherry-picked to `1.7.x`.

I wasn't able to figure out the test-case to check this empty passwords situation.

Although I'm open for any subsequent (within reasonable limits) testing changes.

Thank you for the contribution!

**Pull request closed without merging**
