### PR TITLE
AMQP-537: Blocking methods RabbitTemplate.receive()

### PR DESCRIPTION
**Pull request by Xokker**
JIRA: https://jira.spring.io/browse/AMQP-537

Four new methods in `AmqpTemplate` and `RabbitTemplate`: `receive` and `receiveAndConvert` with timeout arguments.

I have signed and agree to the terms of the SpringSource Individual Contributor License Agreement.

### CODE REVIEW

**Comment by garyrussell** [comment]
Thanks, we need you to "sign" the CLA before we can look at your PR...

https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md

If you've already done so, please indicate here as described there.

Thanks!

**Comment by Xokker** [comment]
@garyrussell done

**Comment by artembilan** [comment]
@Xokker , 

thank you very much for the contribution!

Let us know what works for your better: 
1. We include this feature into the upcoming critical release `1.5.1`, but without `AmqpTemplate` changes just because they are breaking API changes.
2. We deffer the task to the `1.6` version as @garyrussell has done already in the JIRA on the matter.

Anyway we need some tests to be included to the PR, but for the second option you have more time to fix everything. For the first variant we need tests ASAP. Looks like today/tomorrow. :smile:

**Comment by Xokker** [comment]
@artembilan 
Lets defer the task. A project in which those methods will be used (by me) is not in production yet, so I am interested in calmier development. :)

So, what's the plan? Should I write tests for methods which was introduced?

**Comment by artembilan** [comment]
Indeed, @Xokker !
There would be enough to have simple tests for those methods which aren't covered by the existing delegation logic. 
We'll come back to your PR when we switch to the `1.6` deadline.

Thank you one more time for the contribution!

**Comment by artembilan** [comment]
@Xokker ,

we are on the `1.6` dead line already. Please, come back to us with the any update for the PR.

Thank you for the contribution anyway!

**Comment by artembilan** [comment]
@garyrussell , this PR is an old enough, so it may need some our attention.
Since there is no any feeback from @Xokker , I would like to pick up and finish.

From one side we require tests on the matter, but from other side looks like existing methods (without timeout) delegates to the new methods. So, existing tests surely covers new API.
I see that there is need some Copyright and JavaDocs polishing, but they are enough simple.
WDYT?

**Comment by artembilan** [comment]
And yes, Reference Manual as well: http://docs.spring.io/spring-amqp/docs/latest-ga/reference/html/_reference.html#receiving-messages.
So, we really need the proper PR to close the issue finally.

**Comment by garyrussell** [comment]
Yes; I took a quick look Friday - seems simple enough for us to finish.

**Comment by artembilan** [comment]
Closed in favor of #356

**Pull request closed without merging**
