### PR TITLE
Made AmqpAppender.postProcessMessageBeforeSend  protected

### PR DESCRIPTION
**Pull request by Romster**
[Jira](https://jira.spring.io/browse/AMQP-805)
[Issue](https://github.com/spring-projects/spring-amqp/issues/722)

### CODE REVIEW

**Comment by artembilan** [comment]
@Romster ,

Thank you for contribution!

Why did you do the Pull Request against `1.7.x` branch? Wouldn't you like to have it in the `2.1` or at least in the `2.0.x`? I mean why PR is not against `master`? If we need to back port the fix, there is just need to ask to do that. Otherwise it sounds like only the fix for `1.7.x`. Am I missing anything? Thanks

**Comment by artembilan** [comment]
I think the problem was really in a mix of `public` and `protected`.

Yes, it compiles in Java, indeed, but you can't use that `public` method outside of the class because it requires a `protected` type. That's really wrong from usage perspective, but we all live with that in Java for a while. :smile: 

Although I still think that Kotlin has to follow Postel's Law and be tolerant to Java classes it uses.

**Comment by artembilan** [comment]
Thanks, @Romster , for a quick turnaround and explanation!

Well, so far so good: your change not so big to be cherry-picked to `master` and `2.0.x`.

I just wanted to know if we should do that or you had something specific in the mind for them.
Nothing more: just wanted do not confuse if I would going to cherry-pick without confirmation.

So, LGMT, merging...
(With commit message polishing :smile: )

**Comment by Romster** [comment]
@artembilan I'm sorry - what does LGMT mean?:) Never saw this abbreviation.

**Comment by artembilan** [comment]
Oh! My bad. Typo. I wanted to say: Looks Good To Me. 
Gotcha! :smile:

**Comment by Romster** [comment]
@artembilan XD
Great! Thank you! Should I close my issue or do anything else?

**Comment by artembilan** [comment]
No. You are good to go.
Although, wait!

There are many other things requiring a contribution.
So, please, stay and PR them! :wink: 

Thank you so far!

**Comment by artembilan** [comment]
... and cherry-picked to `master` and `2.0.x`

**Pull request merged**
