### PR TITLE
fix issues 794

### PR DESCRIPTION
**Pull request by carl-zhao**
fix issues 794

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@carl-zhao Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-amqp&pullRequestId=803)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-amqp&pullRequestId=803) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by artembilan** [comment]
@carl-zhao ,

Thanks for contribution, but we need to have a CLA signing confirmation before we start reviewing this.

**Comment by artembilan** [comment]
@carl-zhao ,

Gentle ping. We are going to release RC1 tomorrow, so would be great to have this fix there as well, but as you see we can't proceed without signed CLA.

Or we can close your PR and address issue ourselves.

Thanks for understanding.

**Comment by artembilan** [comment]
Closed in favor of #826.

As I said before: we can't accept external contributions without signed CLA.

Thank you for your effort anyway!

**Pull request closed without merging**
