### PR TITLE
[#1145] Fix generic parameter type detection for batch listeners …

### LINKED ISSUE #1145: Batch listening does not work for typed Spring messaging messages
**Affects Version(s): 2.2.2.RELEASE**

## Bug report

The following batch listener does not work as expected:

```java
@RabbitListener(queues = "aQueue")
public void receive(List<Message<Foo>> batch) {
  batch.forEach(message -> System.out.println(message.getPayload().toString()));
}
```

Incoming messages fail to get deserialized with the following error message:
```
org.springframework.amqp.rabbit.support.ListenerExecutionFailedException: Listener threw exception
[...]
Caused by: org.springframework.amqp.support.converter.MessageConversionException: Failed to convert Message content
[...]
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.springframework.messaging.Message` (no Creators, like default construct, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: (String)"{"test": 1}"; line: 1, column: 1]
```

## Steps to reproduce

```java
@SpringBootApplication
@EnableRabbit
public class SpringAmqpBatchMessageBug {

  public static void main(String[] args) throws Exception {
    ConfigurableApplicationContext context = SpringApplication.run(SpringAmqpBatchMessageBug.class, args);
    RabbitTemplate rabbitTemplate = context.getBean(RabbitTemplate.class);
    rabbitTemplate.send("exchange", "", msg("{\"test\": 1}"));
    rabbitTemplate.send("exchange", "", msg("{\"test\": 2}"));
    rabbitTemplate.send("exchange", "", msg("{\"test\": 3}"));
    context.getBean(Listener.class).latch.await(60, TimeUnit.SECONDS);
    context.close();
  }

  private static org.springframework.amqp.core.Message msg(String body) throws UnsupportedEncodingException {
    MessageProperties properties = new MessageProperties();
    properties.setContentType("application/json");
    return new org.springframework.amqp.core.Message(body.getBytes(SimpleMessageConverter.DEFAULT_CHARSET), properties);
  }

  @Bean
  public FanoutExchange exchange() { return (FanoutExchange) ExchangeBuilder.fanoutExchange("exchange").build(); }
  @Bean
  public Queue workingBatchQueue() { return new Queue("workingBatchQueue"); }
  @Bean
  public Queue brokenBatchQueue() { return new Queue("brokenBatchQueue"); }
  @Bean
  public Binding workingQueueBinding(Queue workingBatchQueue, FanoutExchange exchange) { return BindingBuilder.bind(workingBatchQueue).to(exchange); }
  @Bean
  public Binding brokenQueueBinding(Queue brokenBatchQueue, FanoutExchange exchange) { return BindingBuilder.bind(brokenBatchQueue).to(exchange); }

  @Bean
  public SimpleRabbitListenerContainerFactory simpleRabbitListenerContainerFactory(
      SimpleRabbitListenerContainerFactoryConfigurer configurer,
      ConnectionFactory connectionFactory) {
    SimpleRabbitListenerContainerFactory factory = new SimpleRabbitListenerContainerFactory();
    configurer.configure(factory, connectionFactory);
    factory.setConnectionFactory(connectionFactory);
    factory.setMessageConverter(new Jackson2JsonMessageConverter());
    factory.setBatchListener(true);
    factory.setConsumerBatchEnabled(true);
    factory.setDeBatchingEnabled(true);
    factory.setBatchSize(3);
    factory.setReceiveTimeout(1000L);
    return factory;
  }

  @Bean
  public Listener listener() {
    return new Listener();
  }

  public static class Listener {

    private final CountDownLatch latch = new CountDownLatch(3);

    @RabbitListener(
        queues = "workingBatchQueue",
        containerFactory = "simpleRabbitListenerContainerFactory"
    )
    public void receiveWorkingBatch(List<Foo> batch) {
      System.out.println("Received batch of size " + batch.size() + " from 'workingBatchQueue'");
      batch.forEach(message -> {
        System.out.println("Message in 'workingBatchQueue' batch: " + message);
        latch.countDown();
      });
    }

    @RabbitListener(
        queues = "brokenBatchQueue",
        containerFactory = "simpleRabbitListenerContainerFactory"
    )
    public void receiveBrokenBatch(List<Message<Foo>> batch) {
      System.out.println("Received batch of size " + batch.size() + " from 'brokenBatchQueue'");
      batch.forEach(message -> {
        System.out.println("Message in 'brokenBatchQueue' batch: " + message.getPayload());
        latch.countDown();
      });
    }

  }

  public static class Foo {
    private int test;

    public int getTest() {
      return test;
    }

    public void setTest(int test) {
      this.test = test;
    }

    @Override
    public String toString() {
      return "test: " + test;
    }
  }

}
```

### PR DESCRIPTION
**Pull request by KaiStapel**
… with typed 'org.springframework.messaging.Message's

Proposal to fix #1145

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@KaiStapel Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-amqp&pullRequestId=1146)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-amqp&pullRequestId=1146) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@KaiStapel Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-amqp&pullRequestId=1146)!

**Comment by garyrussell** [comment]
LGTM; thanks; please add your name to the `@author` list in each changed file.

**Comment by KaiStapel** [comment]
Done

**Pull request merged**
