### PR TITLE
Update Reference  Links

### PR DESCRIPTION
**Pull request by ngocnhan-tran1996**
I update some reference links.

I also delete `message-converter-changes-1.adoc` because I think `message-converter-changes-1.adoc` and `message-converter-changes.adoc` are the same.

Please check again and tell me if I miss something.

### CODE REVIEW

**Comment by artembilan** [comment]
@ngocnhan-tran1996 ,

Please, sign CLA first, then we will be able to look into your contribution.

Thanks

**Comment by ngocnhan-tran1996** [comment]
> @ngocnhan-tran1996 ,
> 
> Please, sign CLA first, then we will be able to look into your contribution.
> 
> Thanks

@artembilan 

I signed. Thank you

**Comment by ngocnhan-tran1996** [comment]
> OK. Let's see if this does the trick:
> 
> > [Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-amqp&pullRequestId=2759) to manually synchronize the status of this Pull Request.
> 
> !
> 
> Because the status on PR is still not valid.

Thanks for this trick xD

**Review by artembilan — CHANGES_REQUESTED** [review]
Looks great!

Please, also remove that `message-converter-changes-1.adoc` reference from the `nav.adoc`.

**Comment by ngocnhan-tran1996** [comment]
> Looks great!
> 
> Please, also remove that `message-converter-changes-1.adoc` reference from the `nav.adoc`.

I removed `message-converter-changes-1.adoc` in `nav.adoc`. Please review again.

**Review by artembilan — APPROVED** [review]
When PR build is green, I'll merge this.

Thank you for contribution; looking forward for more!

**Pull request merged**
