### PR TITLE
Fix Async Rabbit Template documentation section

### PR DESCRIPTION
**Pull request by baev**
Currently AsyncRabbitTemplate's section title in documentation looks odd:

Screenshot 2020-12-02 at 16 20 25

The proposed change will align styling of the section title

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@baev Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-amqp&pullRequestId=1277)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-amqp&pullRequestId=1277) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@baev Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-amqp&pullRequestId=1277)!

**Review by artembilan — APPROVED** [review]
I agree. Since this section is too deep in the content tree it doesn't have a number withing its `4.1.10` section. Therefore it really would be better to have it aligned with the previous `Reply Listener Container` paragraph.

**Comment by garyrussell** [comment]
Thanks.

**Pull request merged**
