### PR TITLE
AMQP-485: Fixed docs for SimpleMessageListenerContainer

### PR DESCRIPTION
**Pull request by r1pp3rj4ck**
JIRA ticket: https://jira.spring.io/browse/AMQP-485

### CODE REVIEW

**Comment by artembilan** [comment]
Hi @r1pp3rj4ck !

Thank you for the contribution!

But before we accept your work, we should be sure that you have signed CLA: https://github.com/spring-projects/spring-amqp/wiki

**Comment by r1pp3rj4ck** [comment]
I have signed and agree to the terms of the SpringSource Individual Contributor License Agreement.

Should I cherry-pick this commit in a new topic branch on top of 1.3.x and create a new PR instead of this one?

**Comment by artembilan** [comment]
Thank you very much!

No everything looks good. We'll address cherry-pick on merge.

Looking forward for more contribution!

**Comment by artembilan** [comment]
Merged and cherry-picked

**Comment by r1pp3rj4ck** [comment]
Thank you too, will try to contribute more!

**Pull request closed without merging**
