### PR TITLE
Fix JUnit dependencies

### PR DESCRIPTION
**Pull request by garyrussell**
- eliminate the `platform-commons` dependency
- make the `jupiter-api` dependency optional

### CODE REVIEW

**Comment by artembilan** [comment]
Do you confirm that this works well with IO Platform?
And I'll merge it!
Thanks

**Comment by garyrussell** [comment]
```
$ ./gradlew clean springIoCheck --continue --no-daemon -PplatformVersion=Cairo-BUILD-SNAPSHOT 
...
BUILD SUCCESSFUL in 30s
9 actionable tasks: 9 executed
```

**Comment by artembilan** [comment]
> BUILD SUCCESSFUL in 30s

??? Looks like you are missing there `-PJDK8_HOME=` option for real testing against IO.
However I'm might missing anything in your decision and that is really enough to do that way...

**Comment by garyrussell** [comment]
Oops - not only did I miss that, I ran it in the wrong window 😄 (against s-k).

**Comment by garyrussell** [comment]
```
$ ./gradlew clean springIoCheck --continue --no-daemon -PplatformVersion=Cairo-BUILD-SNAPSHOT -PJDK8_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/
...
BUILD SUCCESSFUL in 10m 17s
43 actionable tasks: 43 executed
```

**Pull request merged**
