### PR TITLE
AMQP-654: DMLC: Recover from Broker Interruption

### PR DESCRIPTION
**Pull request by garyrussell**
JIRA: https://jira.spring.io/browse/AMQP-654

### CODE REVIEW

**Comment by kartoffelsup** [comment]
You can terminate the stream with a forEach, the collect operation is redundant. You are basically iterating twice.

**Comment by garyrussell** [comment]
@kartoffelsup Thanks for reviewing.

Unfortunately not; the `cancelConsumer()` method modifies `this.consumers` so we will get a `ConcurrentModificationException`.

I anticipated such a suggestion and considered adding a comment to the `collect()`. I guess I should have done so.

**Comment by kartoffelsup** [comment]
Makes sense, sorry - didn't catch that! A comment really sounds like a good idea here though :)

**Comment by artembilan** [comment]
LGTM.
Merging...

@kartoffelsup , thank you very much for review!

**Comment by artembilan** [comment]
Merged as https://github.com/spring-projects/spring-amqp/commit/7aa924e9ec502361cf6c287750eaf3eeac473b03

**Pull request closed without merging**
