### PR TITLE
More Sonar Fixes

### PR DESCRIPTION
**Pull request by garyrussell**

### CODE REVIEW

**Comment by artembilan** [comment]
Please, resolve deprecations and tests failure according the Travis report.

**Comment by garyrussell** [comment]
Not related, I think, but I did find a bug in the first test.

**Comment by artembilan** [comment]
This one is still failing:
```
org.springframework.amqp.rabbit.core.RabbitTemplatePublisherCallbacksIntegrationTests > testPublisherConfirmReceived FAILED
    java.lang.AssertionError at RabbitTemplatePublisherCallbacksIntegrationTests.java:203
```

Or do you mean that we should merge this and let's fix the test separately ?

**Comment by garyrussell** [comment]
Let me look at it

**Pull request merged**
