### PR TITLE
Expose json object mapper through getter

### PR DESCRIPTION
**Pull request by calvernaz**
This patch address the issue opened in #589

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@calvernaz Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-amqp&pullRequestId=590)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-amqp&pullRequestId=590) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by artembilan** [comment]
@calvernaz,

Please, come back to us with a signed CLA.
Otherwise we can't review and accept your PR.

I understand that it might seem like an "obvious fix", but at a glance it is really with some flaws and would be really better to pass `objectMapper` as an argument to the `initializeJsonObjectMapper()`.
I'd even rename it into `initializeDefaultJsonObjectMapper()`, because that won't be good to let to mutate the provided `ObjectMapper`.
Although the getter must be there anyway.

Thank you for your contribution effort!

**Comment by calvernaz** [comment]
I signed it already, I got the message:

_Thank you for signing the Agreement! The contributor license agreement checks on spring-projects/spring-amqp/pull/590 should now pass._

Yea, I thought about that suggestion, but I had doubts about changing the API and decided to go with the protected getter to leave just enough room for access.

Saying that I can follow up and accommodate all those suggestions.

**Comment by pivotal-issuemaster** [comment]
@calvernaz Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-amqp&pullRequestId=590)!

**Comment by artembilan** [comment]
OK! After manual PR syncing we really see a confirmation.

Right that looks like a breaking change, but my concern to let end user to know that we configure with that method only a default `ObjectMapper` instance. 
If you provide an external one, that is already your responsibility to configure it there.
We can't mutate an external instance unconditionally and changing the API that should be much cleaner now.

I won't mind any other opinion.

**Comment by artembilan** [comment]
@garyrussell ,

Your opinion on the matter?
This is the last community PR (and its issue) we should consider for tomorrow's release.
Thanks.

**Comment by garyrussell** [comment]
@artembilan I am not sure what you mean by "breaking change" - all we're doing is adding a getter to allow a subclass to access the field rather than replacing the default mapper.

The structure of this class is a little odd; normally you should only call final methods from a ctor, explicitly to prevent subclasses from changing expected behavior.

Personally, I would make the mapper final and add another ctor that takes a fully assembled mapper. We could deprecate the setter in 1.7.x and change the javadoc to make it clear the `initialize...` method is only called from the default ctor.

Another alternative would be to deprecate that initialize method and add a new one that takes the mapper as an argument.

**Comment by artembilan** [comment]
Thank you, @garyrussell , for your vision!

Well, at least we are on the same page about the oddity of this class 😄 

How about this: https://github.com/artembilan/spring-amqp/commit/99bc3b95d42b209dcced7c8dda583d5bad2110c7 ?

I didn't make it as a `final` do not break existing extensions. But this might be candidate really for `1.7.x`.
In the `2.0` we can remove those deprecated methods and make the property `final`.

IMO the class isn't designed for extension and it doesn't aim that goal by the purpose.
So, simple injection of externally configured `ObjectMapper` should be as a silver bullet.

**Comment by garyrussell** [comment]
LGTM (with javadocs on the ctors that is 😄 )

**Comment by artembilan** [comment]
> LGTM

Sorry, not enough info. 
Does that mean that we apply it as is for `master`? Or what I did is for `1.7.x`? The `master` version should be provided.
Thanks

**Comment by garyrussell** [comment]
Sorry; yes; I meant apply this with deprecations to 1.7.x and remove them in 2.0.

**Comment by artembilan** [comment]
Good, thank you, Gary, for confirmation!

@calvernaz ,

Sorry, since you see a discussion, this PR becomes unrelated.

Please, close it and let us know if you are good to provide a couple new:
1. For `1.7.x` with my change in that commit
2. For `master` with similar change but with removed `@Deprecated` methods and `final` for the `objectMapper` property.

We need it for tomorrow: the release obligations.

Otherwise let us know and we do that for you.

There are still enough tasks for contribution! 😄

**Comment by calvernaz** [comment]
I've been following along the discussion and the constructor option is my favorite solution for this one.

**Comment by artembilan** [comment]
Superseded with the https://github.com/spring-projects/spring-amqp/commit/710464367e15c9287e4f83de40b833c0e632d66c for `1.7.x` and https://github.com/spring-projects/spring-amqp/commit/13e0b7621a93124938a3e7f8f8ed0ef0b60ca8bb for the `master`.

**Pull request closed without merging**
