### PR TITLE
squid:S1854 - Dead stores should be removed

### PR DESCRIPTION
**Pull request by m-ezzat**
This pull request is focused on resolving occurrences of Sonar rule squid:S1854 - Dead stores should be removed

You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S1854
https://jira.spring.io/browse/AMQP-571

Please let me know if you have any questions.

M-Ezzat

### CODE REVIEW

**Comment by artembilan** [comment]
Hello, @m-ezzat !

Would you mind to remind me if you have signed the [CLA](https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.adoc)?

We can't review without that confirmation.

Thanks

**Comment by m-ezzat** [comment]
Hello @artembilan,

yes, I've signed up, and here is my confirmation number 162120160208042823

**Comment by artembilan** [comment]
OK. Thank you for letting to know and for the fix as well.
Merging...

Looking forward for more!

**Comment by artembilan** [comment]
Merged as https://github.com/spring-projects/spring-amqp/commit/425425a000d5c6d5bb369ab2d8c5d1656d2fbb6a

**Pull request closed without merging**
