### PR TITLE
AMQP-688: Remove Jackson 1 support

### PR DESCRIPTION
**Pull request by artembilan**
JIRA: https://jira.spring.io/browse/AMQP-688

Since Jackson 1 is deprecated for a while it is safe just drop its support in the current major `2.0` version.

### CODE REVIEW

**Comment by garyrussell** [comment]
Perhaps a "what's new" entry ?

**Comment by artembilan** [comment]
Sure thing! 😄

**Comment by artembilan** [comment]
Pushed `What's New`

**Comment by garyrussell** [comment]
Merged with minor doc polish as a82b78620c5502f5b98815868c2defc8b30cf9ff

**Pull request closed without merging**
