### PR TITLE
Fix tearDown method in testing.adoc code example

### PR DESCRIPTION
**Pull request by liry**
Obvious Fix

`@AfterClass` method has to be static or else Exception is thrown.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@liry Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-amqp&pullRequestId=586)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-amqp&pullRequestId=586) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by liry** [comment]
ok to test @

**Comment by liry** [comment]
ok to test

**Comment by pivotal-issuemaster** [comment]
@liry Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-amqp&pullRequestId=586)!

**Comment by artembilan** [comment]
Thanks.
Looking forward for more!

**Pull request merged**
