### PR TITLE
AMQP-580: Add Bean Name to Default Task Executor

### PR DESCRIPTION
**Pull request by garyrussell**
JIRA: https://jira.spring.io/browse/AMQP-580

Identify the originating container/consumer in logs.

### CODE REVIEW

**Comment by artembilan** [comment]
I wonder if Travis report tells you anything...

**Comment by garyrussell** [comment]
No; builds ok locally - however, the delayed exchange test fails sometimes; pushed a change for that.

**Comment by artembilan** [comment]
LGTM, but consider, please, this inclusion: https://github.com/artembilan/spring-amqp/commit/84a474f57331dfe1ac5a95e65dca1a4adc2a98d7

**Comment by garyrussell** [comment]
Thanks; good idea; pushed with a little polish.

**Comment by artembilan** [comment]
Merged as https://github.com/spring-projects/spring-amqp/commit/df7b5aa2f5cdb5e9c0982689cc08bc9670f2f44a

**Pull request closed without merging**
