### PR TITLE
AMQP-606: Increase Default Channel Cache Size

### PR DESCRIPTION
**Pull request by garyrussell**
JIRA: https://jira.spring.io/browse/AMQP-606

### CODE REVIEW

**Comment by artembilan** [comment]
I see that Travis failure isn't related to your changes and is just sporadic timing issue around `this.template.setReplyTimeout(10000);`.

I wonder if we should mark those ` warning: [deprecation]` methods with the `@Deprecated` or can we overcome that somehow with some `compilerArgs` options?
Or just live as is...

Otherwise LGTM and I am ready to merge.

**Comment by artembilan** [comment]
`-processing` helps to avoid the compiling noise like:
```
warning: No processor claimed any of these annotations: org.springframework.jmx.export.annotation.ManagedMetric,org.springframework.context.annotation.Import,
```
I can add on merge.

**Comment by garyrussell** [comment]
Strange - I don't see those deprecation warnings locally.

**Comment by artembilan** [comment]
OK. Merging with `-processing` `-Xlint` option.
M-m-m. And I remove the Checkstyle fixers scripts.
Good ?

**Comment by garyrussell** [comment]
👍

**Comment by artembilan** [comment]
Merged as https://github.com/spring-projects/spring-amqp/commit/fddbdf7100ed0e444f74bbf7fa660a7a5d2dfc8f

**Pull request closed without merging**
