### PR TITLE
Add missing `@Nullable`

### LINKED ISSUE #871: Invalid @NonNullApi and null return
Hi,

I have noticed an invalid nullable situation within spring-rabbit's API.

At least the method `org.springframework.amqp.rabbit.core.RabbitAdmin#getQueueProperties` is nullable (I think it was nullable alway as I'm using this for explicit queue management on startup for years) as the code clearly shows (in the local exception handling) as well as the documentation clearly states 

```
Returns 3 properties {@link #QUEUE_NAME}, {@link #QUEUE_MESSAGE_COUNT},
{@link #QUEUE_CONSUMER_COUNT}, or null if the queue doesn't exist.
```

However, the package contains a `@NonNullApi` also. And as I had understand this correctly, either this one is not correct, or there is a `@Nullable` missing, or the code should not return `null`. 

The issue got into my attention as IntelliJ hints about a redundant null check. Fortunately, I have checked this.

### PR DESCRIPTION
**Pull request by knalli**
Resolves #871

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@knalli Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-amqp&pullRequestId=872)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-amqp&pullRequestId=872) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@knalli Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-amqp&pullRequestId=872)!

**Comment by knalli** [comment]
Also, I have added a second commit covering `ChannelCallback`, but also some missing (impl vs api) `AmqpTemplate` and `RabbitTemplate`.

**Comment by garyrussell** [comment]
LGTM; @knalli Many thanks for your help with this.

We are committed to addressing all of these issues over time, in particular to provide a better experience for Kotlin users; help like this will assist us with expediting those efforts.

**Comment by knalli** [comment]
> However there is a Checkstyle failure on Travis: 

Oops, was not aware of that. Should I rebase everything into one?

**Comment by artembilan** [comment]
No need to worry about rebase and squash. We do that on merge, if there are not critical conflicts.

Thank you for contribution, @knalli 
Looking forward for more!

**Pull request merged**
