### PR TITLE
GH-933: Fix NPE in PublisherCallbackChannelImpl

### PR DESCRIPTION
**Pull request by garyrussell**
Fixes https://github.com/spring-projects/spring-amqp/issues/933

**cherry-pick to 2.1.x**

### CODE REVIEW

**Comment by artembilan** [comment]
Gary, does Travis report say anything to you:

```
org.springframework.amqp.rabbit.core.RabbitTemplateIntegrationTests > testReceiveInExternalTransactionAutoAck FAILED
    java.lang.AssertionError at RabbitTemplateIntegrationTests.java:600

```
?

**Comment by artembilan** [comment]
I don't see how your change affects that test, so I don't mind to merge this.
Just let me know when!

**Comment by garyrussell** [comment]
I'll take a look at it; it built cleanly for me but we might as well fix it.

**Comment by artembilan** [comment]
... and cherry-picked to `2.1.x`.

So, I have missed to squash for `master` again 😢

**Pull request merged**
