### PR TITLE
GH-967: Use `ChannelProxy` CL instead of context

### PR DESCRIPTION
**Pull request by artembilan**
Fixes https://github.com/spring-projects/spring-amqp/issues/967

**Cherry-pick to 2.1.x**

### CODE REVIEW

**Comment by garyrussell** [comment]
Checkstyle

**Comment by garyrussell** [comment]
```
org.springframework.amqp.rabbit.annotation.EnableRabbitIntegrationTests > deadLetterOnDefaultExchange FAILED
    org.junit.ComparisonFailure at EnableRabbitIntegrationTests.java:739
org.springframework.amqp.rabbit.annotation.ComplexTypeJsonIntegrationTests > executionError FAILED
    java.lang.IllegalStateException
        Caused by: org.springframework.context.ApplicationContextException
            Caused by: org.springframework.amqp.AmqpIllegalStateException
                Caused by: org.springframework.amqp.rabbit.listener.QueuesNotAvailableException
                    Caused by: org.springframework.amqp.rabbit.listener.BlockingQueueConsumer$DeclarationException
                        Caused by: java.io.IOException
                            Caused by: com.rabbitmq.client.ShutdownSignalException
                                Caused by: com.rabbitmq.client.ShutdownSignalException
```

**Comment by artembilan** [comment]
Doesn't fail for me locally:

изображение


I guess this is the same SF Testing issue.
So, locally I don't have a fresh version.

But that all doesn't mean that we are good to merge, since it is going to fail on CI server anyway.

**Comment by garyrussell** [comment]
Yeah - I figured that after I added the comment; not worth merging anything until the issue is resolved.

**Comment by artembilan** [comment]
So, it's green finally on Travis. 😄

**Comment by garyrussell** [comment]
Cherry-picked as 85ddd2886c0826ba91c231cdd67eb666c114ac74

**Pull request merged**
